name: CRON workflow

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  invalidation:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        run: |
          echo test

