name: Email Notification Workflow
on:
  workflow_run:
    types:
      - in_progress

jobs:
  sendMail:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Send mail
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: email-smtp.eu-west-1.amazonaws.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: GitHub Actions build
        # Use body: field or body_file: can't be both
        body: Build of project was completed successfully!
        to: chayma.bh@tempest.com
        from: Your Github Notif
        # Optional carbon copy recipients
        # cc: cc@example.com
        # Optional blind carbon copy recipients
        # bcc: bcc@example.com
        # Optional content type (defaults to text/plain)
        content_type: text/html
