name: Email Notification requested
on:
  workflow_run:
    workflows: [AWS, CRON workflow]
    types:
      - requested
jobs:
  sendMail:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Send mail
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: email-smtp.eu-west-1.amazonaws.com
        server_port: 587
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: GitHub Actions build
        # Use body: field or body_file: can't be both
        body: Build job of ${{github.repository}} was completed successfully!
        to: chayma.bh@tempest.com
        from: User <sentry@tempest.com>
        # Optional carbon copy recipients
        # cc: cc@example.com
        # Optional blind carbon copy recipients
        # bcc: bcc@example.com
        # Optional content type (defaults to text/plain)

#    - name: Send some mail
#      uses: wadeww/send-email-action@master
#      with:
#        server_address: email-smtp.eu-west-1.amazonaws.com
#        port: 587
#        username: ${{secrets.MAIL_USERNAME}}
#        password: ${{secrets.MAIL_PASSWORD}}
#        subject: Workflow finished
#        body: Job completed ${{job.status}}
#        to: chayma.bh@tempest.com
#        from: Me
